'use client'
import React, {useRef} from "react";
import Image from "next/image";
import {Table} from "antd";
import dayjs from "dayjs";
import {Salary} from "@/app/db/queries/salary";

const currentDate = dayjs(); // Ambil tanggal dan waktu saat ini
const formattedDate = currentDate.format('DD MMMM YYYY HH:mm [WIB]');

export default function SalaryExport({datas}: { datas: Salary[] }) {
    const componentRef = useRef(null);
    const columns : any= [
        {
            title: "NIK",
            dataIndex: "karyawanNik",
            key: "nik",
        },
        {
            title: "Bulan",
            dataIndex: "month",
            key: "month",
            render: (date: any) => dayjs(date).format("MMM YYYY"),
        },
        {
            title: "Gaji Pokok",
            dataIndex: "baseSalary",
            key: "baseSalary",
            render: (value: any) => `Rp ${value.toLocaleString()}`,
        },
        {
            title: "Potongan Absen",
            dataIndex: "absenDeduction",
            key: "absenDeduction",
            render: (value: any) => `Rp ${value.toLocaleString()}`,
        },
        {
            title: "Bonus",
            dataIndex: "bonusSalary",
            key: "bonusSalary",
            render: (value: any) => `Rp ${value.toLocaleString()}`,
        },
        {
            title: "Uang Makan",
            dataIndex: "foodSalary",
            key: "foodSalary",
            render: (value: any) => `Rp ${value.toLocaleString()}`,
        },
        {
            title: "Potongan Pinjaman",
            dataIndex: "loan",
            key: "loan",
            render: (value: any) => `Rp ${value.toLocaleString()}`,
        },
        {
            title: "Total Hari Kerja",
            dataIndex: "totalDayWork",
            key: "totalDayWork",
            render: (value: any) => `${value.toLocaleString()} Hari`,
        },
        {
            title: "Total Tidak Hadir",
            key: "absenTotal",
            // dataIndex: "totalSick",
            render: (value: any) => `${(value.totalSick+ value.totalAlpha).toLocaleString()} Hari`,
        },
        // {
        //     title: "Total Sick Days",
        //     dataIndex: "totalSick",
        //     key: "totalSick",
        // },
        {
            title: "Total Gaji Bersih",
            dataIndex: "totalSalary",
            key: "totalSalary",
            render: (value: any) => `Rp ${value.toLocaleString()}`,
        },
        // {
        //     title: "Generated By",
        //     dataIndex: "generatedBy",
        //     key: "generatedBy",
        // },
        // {
        //     title: "Created At",
        //     dataIndex: "createdAt",
        //     key: "createdAt",
        //     render: (date: any) => dayjs(date).format("DD MMM YYYY"),
        // },
    ];

    return (
        <div className={`border bottom-0 border-gray-300 w-full p-3 gap-3 text-sm mb-2 flex-grow`}>
            <div ref={componentRef} className={`text-black text-sm`}>
                <div className="w-full flex flex-col">
                    <div className={`flex gap-4 items-center print-header`}>
                        <Image src={'/logos.png'} alt={'Logo'} width={120} height={120}/>
                        <div className={`flex flex-col`}>
                            <h2 className="font-bold text-xl">Data Gaji Karyawan</h2>
                            <h3>Tanggal : {formattedDate}</h3>
                        </div>
                    </div>
                    <Table
                        bordered
                        style={{
                            width: "100%",
                        }}
                        rowKey={'part'}
                        columns={columns}
                        components={{
                            body: {
                                cell: (props: any) => {
                                    return <td {...props} style={{padding: '4px 8px'}}/>;
                                },
                            },
                        }}
                        rowClassName={'text-[12px]'}
                        dataSource={datas}
                        pagination={false}
                        size={'small'}/>
                </div>
            </div>
        </div>
    )
}