import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {ConfigProvider} from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Payroll System",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#010031',
            },
            components: {
              Card: {
                // colorBgContainer: '#383773'
              },
              Layout: {
                footerPadding: '5px',
                  footerBg:'#010031',
                // bodyBg: '#292751',
                // footerBg: 'url("/images/batik5.png")',
                opacityImage: 10,
                siderBg: '#151441',
                headerColor: 'white',
                // headerBg: 'url("/images/batik5.png")',
              },
              Menu: {
                // itemBg: '#18316A',
                darkItemBg: '#010031',
                itemSelectedBg: '#071b4a',
                darkItemSelectedBg: '#010031'
              },
              Table: {
                cellPaddingBlock: 2,
                cellPaddingBlockSM: 6,
                rowSelectedBg: '#F2ECFF',
                rowHoverBg: '#F2ECFF',
                rowSelectedHoverBg: '#F2ECFF',
                colorText: 'black',
                // rowSelectedBg: 'red'
              },
            },
          }}
      >
        <AntdRegistry>
          {
            children
          }
        </AntdRegistry>
      </ConfigProvider>
      </body>
      </html>
  );
}
